### ISSUE TITLE
Implement a "Remove All" command please?

### ISSUE THREAD

**Issue by Naereen** [redoPop/SublimeGremlins#1]
Hi,

That is a great plugin! And such a cool name :clap: !

Could I suggest one more function/palette command please?
It could be verty useful to have a "Remove All" command to quickly remove all the nasty gremlins :japanese_ogre: , instead of removing them one by one.

Thanks in advance :wave: !

**Comment by Naereen** [comment]
Any update?

**Comment by Naereen** [comment]
Any update please ?

**Comment by redoPop** [comment]
Hello! Huge apologies for the long delay: I only recently realized I'd misconfigured my GitHub notifications and have been missing many, including this issue!

One of this this plugin's existing features _may_ satisfy your use case: the "Find All Gremlins" command, which is available in the "Find" menu:

![](https://snap.redopop.com/2017-01-11_18-24_Gremlins.png)

…and also in [the command palette:](http://docs.sublimetext.info/en/latest/extensibility/command_palette.html)

![](https://snap.redopop.com/2017-01-11_18-25_Gremlins.png)

When you use it, _all_ the gremlins in the current document will be selected at once, using [Sublime's multiple selections feature:](http://docs.sublimetext.info/en/latest/editing/editing.html#multiple-selections)

![](https://snap.redopop.com/2017-01-11_18-31_Gremlins.png)

…so pressing the delete button after performing "Find All Gremlins" deletes every gremlin at once.

The reason I chose to implement this, rather than a "Remove All Gremlins" feature, was that my definition of a gremlin encompasses _visible_ ambiguous whitespace characters (e.g. [U+00A0](https://en.wikipedia.org/wiki/Non-breaking_space)) along with those that are narrow or invisible (e.g. [U+200B](https://en.wikipedia.org/wiki/Zero-width_space)). _Removing_ the visible gremlins could collapse words that were previously separated by spaces or create other unforeseen problems, so I wanted to implement a feature that would give users a little more control over their gremlin replacement strategy, and nudge them them to approach gremlin removal more cautiously.

Does this approach seem sufficient, or is a more explicit "Remove All" feature necessary?

**Comment by Naereen** [comment]
Hi,

No issue about the delay, that's why I pinged you again.

And OK for the solution you propose, I think that's also what I have been doing in fact.
Thanks :+1: !
