### ISSUE TITLE
Breaks the highlight when find/replace

### ISSUE THREAD

**Issue by x100ex** [redoPop/SublimeGremlins#4]
When you press "Find" not often, the highlight of the matching string is practically not visible.

When you press "Find" very often, you can see that at first the highlight is yellow, and then instantly the backlight changes to an almost invisible one, merging with the background.

<details>
  <summary>GIF</summary>
  
![43016823-8d46339c-8c6d-11e8-87df-1a11ccf3f889](https://user-images.githubusercontent.com/1345294/48315133-33e18a00-e5f4-11e8-9286-9df724aba36a.gif)

</details>

**Comment by redoPop** [comment]
The gif is very helpful. It looks like the find tool's text highlight is being converted to a regular text selection. I was unable to replicate the issue at first, but realized it's just that text selections have a much stronger contrast in my own theme: it's happening to me too but I just haven't been noticing.

Sublime Gremlins [uses the `on_selection_modified_async` event](https://github.com/redoPop/SublimeGremlins/blob/d0389a29d3ac379f6417f8a838380cf6fa4ba6fd/Gremlins.py#L174-L175) to detect when the cursor is over a gremlin, so that's my lead; something in [the ensuing command](https://github.com/redoPop/SublimeGremlins/blob/d0389a29d3ac379f6417f8a838380cf6fa4ba6fd/Gremlins.py#L106-L132) must be breaking the highlight.

**Comment by redoPop** [comment]
The fix in #5 has been merged and released as version 1.0.0 of the package.

Thanks for filing this issue!
